language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test
after_success:
  - make docker_build
  - PASSWORD=$DOCKER_PASSWORD make docker_push

deploy:
  provider: heroku
  api_key: hello-world-printer-app
  secure: ${HEROKU_API_KEY}
